apiVersion: v1
kind: Template
metadata:
  name:   
  annotations:
    description: "This is Stub API"
    openshift.io/display-name: "Stub API"
    version: 0.3.0
    tags: stub,thoth,api,ai-stacks
    template.openshift.io/documentation-url: "https://github.com/Thoth-Station/"
    template.openshift.io/long-description: "This is Stub API"
    template.openshift.io/provider-display-name: "Red Hat, Inc."
  labels:
    template: stub-api-deployment
    app: stub
    component: stub-api

objects:
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: stub-api
      labels:
        app: stub
        component: stub-openapi
    spec:
      port:
        targetPort: http
      to:
        kind: Service
        name: stub-openapi

  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: stub
        component: openapi
      name: stub-openapi
    spec:
      ports:
        - name: http
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        service: stub-api

  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: stub
        component: grpc
      name: stub-grpc
    spec:
      type: ClusterIP
      ports:
        - name: grpc
          port: 8443
          protocol: TCP
          targetPort: 8443
      selector:
        service: stub-api

  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      labels:
        app: stub
        component: stub-api
      name: stub-api
    spec:
      replicas: 1
      selector:
        service: stub-api
      template:
        metadata:
          labels:
            service: stub-api
        spec:
          serviceAccountName: stub
          containers:
            - name: stub-openapi
              image: stub-api
              env:
                - name: APP_MODULE
                  value: 'thoth.stub.openapi_server:app'
                - name: STUB_API_APP_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: stub
                      key: app-secret-key
                - name: SENTRY_DSN
                  valueFrom:
                    secretKeyRef:
                      name: stub
                      key: sentry-dsn
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources:
                requests:
                  memory: "384Mi"
                  cpu: "125m"
                limits:
                  memory: "384Mi"
                  cpu: "500m"
              readinessProbe:
                httpGet:
                  path: '/readiness'
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 5
                periodSeconds: 10
                timeoutSeconds: 10
              livenessProbe:
                httpGet:
                  path: '/liveness'
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 5
                periodSeconds: 60
                timeoutSeconds: 10
            - name: stub-grpc
              image: stub-api
              env:
                - name: APP_FILE
                  value: 'thoth/stub/grpc_server.py'
                - name: STUB_API_APP_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: stub
                      key: app-secret-key
                - name: SENTRY_DSN
                  valueFrom:
                    secretKeyRef:
                      name: stub
                      key: sentry-dsn
              ports:
                - containerPort: 8443
                  protocol: TCP
              resources:
                requests:
                  memory: "384Mi"
                  cpu: "125m"
                limits:
                  memory: "384Mi"
                  cpu: "500m"
              volumeMounts:
                - mountPath: /opt/app-root/src/certs
                  name: stub-grpc-tls
                  readOnly: true
          volumes:
            - name: stub-grpc-tls
              secret:
                defaultMode: 420
                secretName: stub-grpc
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - stub-openapi
              - stub-grpc
            from:
              kind: ImageStreamTag
              name: 'stub-api:latest'

  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      labels:
        app: stub
        component: stub-api
      name: stub-api
    spec:
      name: latest
      lookupPolicy:
        local: true
