apiVersion: v1
kind: Template
metadata:
  name: stub-api-deployment
  annotations:
    description: "This is Stub API"
    openshift.io/display-name: "Stub API"
    version: 0.2.0
    tags: stub,thoth,api,ai-stacks
    template.openshift.io/documentation-url: "https://github.com/Thoth-Station/"
    template.openshift.io/long-description: "This is Stub API"
    template.openshift.io/provider-display-name: "Red Hat, Inc."
  labels:
    template: stub-api-secrets
    app: stub
    component: secrets

parameters:
  - description: Secret key for flask application to have secured session connections.
    displayName: App secret key
    required: true
    name: STUB_API_APP_SECRET_KEY

  - displayName: SENTRY_DSN
    description: A DSN to a Sentry instance to log to.
    name: SENTRY_DSN
    required: false

objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: stub
      labels:
        app: stub
        component: secrets
    stringData:
      app-secret-key: ${STUB_API_APP_SECRET_KEY}
      sentry-dsn: ${SENTRY_DSN}

